version: '3'
services:
  etcd01:
    image: quay.io/coreos/etcd:latest
    container_name: etcd01
    volumes:
      - ./data/01:/etcd-data
    ports:
      - "2385:2379"
      - "2386:2380"
    expose:
      - 2379
      - 2380
    networks:
      - etcd_net
    environment:
      - ETCDCTL_API=3
    command:
      - /usr/local/bin/etcd
      - --data-dir=/etcd-data
      - --name=etcd01
      - --initial-advertise-peer-urls=http://etcd01:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://etcd01:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --initial-cluster=etcd01=http://etcd01:2380,etcd02=http://etcd02:2380,etcd03=http://etcd03:2380
      - --initial-cluster-state=new
      - --initial-cluster-token=docker-etcd
  etcd02:
    image: quay.io/coreos/etcd:latest
    container_name: etcd02
    volumes:
      - ./data/02:/etcd-data
    ports:
      - "2381:2379"
      - "2382:2380"
    expose:
      - 2379
      - 2380
    networks:
      - etcd_net
    environment:
      - ETCDCTL_API=3
    command:
      - /usr/local/bin/etcd
      - --data-dir=/etcd-data
      - --name=etcd02
      - --initial-advertise-peer-urls=http://etcd02:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://etcd02:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --initial-cluster=etcd01=http://etcd01:2380,etcd02=http://etcd02:2380,etcd03=http://etcd03:2380
      - --initial-cluster-state=new
      - --initial-cluster-token=docker-etcd
  etcd03:
    image: quay.io/coreos/etcd:latest
    container_name: etcd03
    volumes:
      - ./data/03:/etcd-data
    ports:
      - "2383:2379"
      - "2384:2380"
    expose:
      - 2379
      - 2380
    networks:
      - etcd_net
    environment:
      - ETCDCTL_API=3
    command:
      - /usr/local/bin/etcd
      - --data-dir=/etcd-data
      - --name=etcd03
      - --initial-advertise-peer-urls=http://etcd03:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://etcd03:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --initial-cluster=etcd01=http://etcd01:2380,etcd02=http://etcd02:2380,etcd03=http://etcd03:2380
      - --initial-cluster-state=new
      - --initial-cluster-token=docker-etcd

networks:
  etcd_net:
